-- Схема сервиса answers.
--
-- ОТДЕЛЬНАЯ СХЕМА, А НЕ ОТДЕЛЬНАЯ БАЗА.
-- Разные базы дали бы полную изоляцию, но и второй StatefulSet, второй
-- бэкап, второй пул соединений — за это надо платить чем-то реальным.
-- Схема даёт главное: свой namespace имён и возможность выдать сервису
-- права ТОЛЬКО на неё (GRANT USAGE ON SCHEMA answers), то есть
-- least privilege на уровне БД. Переезд схемы в отдельную базу позже —
-- это pg_dump -n answers, а не переписывание кода.
CREATE SCHEMA IF NOT EXISTS answers;

CREATE TABLE IF NOT EXISTS answers.answers (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- event_id UNIQUE — ключ идемпотентности и единственная защита
    -- от дублей при at-least-once доставке Kafka.
    --
    -- Почему на уровне БД, а не «проверим SELECT-ом перед вставкой»:
    -- SELECT + INSERT — это гонка. Два пода answers, получившие один
    -- и тот же повтор одновременно, оба увидят «записи нет» и оба
    -- вставят. UNIQUE-ограничение выполняет проверку атомарно,
    -- и вставка превращается в ON CONFLICT DO NOTHING.
    event_id    TEXT        NOT NULL UNIQUE,

    -- user_id БЕЗ внешнего ключа на users.users — намеренно.
    --
    -- FK связал бы схемы двух сервисов: миграция users смогла бы
    -- заблокировать таблицу answers, а удаление пользователя — молча
    -- каскадно снести историю, о которой users ничего не знает.
    -- Между сервисами ссылочная целостность обеспечивается контрактом
    -- (событие приходит только для существующего пользователя,
    -- telegram-api это проверяет), а не средствами БД.
    -- Цена: возможны «осиротевшие» ответы. Для аналитики это лучше,
    -- чем потеря истории при удалении пользователя.
    user_id     BIGINT      NOT NULL,
    telegram_id BIGINT      NOT NULL,

    question    TEXT        NOT NULL,
    answer      TEXT        NOT NULL,

    -- occurred_at — когда человек ответил (из события).
    -- created_at — когда мы это записали.
    -- Две разные величины: при переигрывании топика или при отставании
    -- потребителя они разъезжаются на часы. Аналитика обязана считать
    -- по occurred_at, иначе «всплеск активности» окажется всплеском
    -- работы потребителя после инцидента.
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- request_id для сквозного поиска по логам (Фактор 11).
    request_id  TEXT        NOT NULL DEFAULT ''
);

-- Индекс под единственный запрос на чтение: «последние ответы пользователя».
-- Порядок колонок повторяет порядок в WHERE + ORDER BY.
CREATE INDEX IF NOT EXISTS answers_user_occurred_idx
    ON answers.answers (user_id, occurred_at DESC);
